In [23]:
import nb_utils
proj_dir = nb_utils.proj_path_setup()

In [24]:
#standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

plt.style.use('ggplot')

%matplotlib inline

In [25]:
train_df = pd.read_csv(os.path.join(proj_dir, 'data', 'raw', 'train.csv'))
test_df = pd.read_csv(os.path.join(proj_dir, 'data', 'raw', 'test.csv'))
feature_cols = [col for col in test_df.columns if col != 'id']

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scaler = StandardScaler()

X_train = scaler.fit_transform(train_df[feature_cols])

y_train = np.array(train_df['target'])

In [28]:
X_train

array([[-0.73403157,  0.36562268, -0.8897276 , -0.88438794, -1.13486936,
        -0.82913603],
       [ 1.06590369, -0.86589692,  0.21952069,  0.28805926,  0.84638411,
         0.02033832],
       [-1.33400999,  0.27208954, -1.19690404,  0.40796863, -0.8780402 ,
         1.53258937],
       ...,
       [ 0.01594146,  0.50592238, -0.83853152,  0.10153357, -0.06352489,
         1.109408  ],
       [-1.48400459,  1.81538625, -1.39315566, -1.17749974, -1.49443017,
        -0.9598244 ],
       [-1.03402078,  0.27208954, -1.22676842, -1.53722786, -0.8780402 ,
        -1.1963081 ]])

In [29]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)

LogisticRegression()

In [32]:
y_train_pred = lr_model.predict(X_train)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_train_pred)

0.7222222222222222

In [14]:
X_test = scaler.transform(test_df[feature_cols])

In [15]:
y_pred = lr_model.predict(X_test)

In [16]:
y_pred

array([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0], dtype=int64)

In [20]:
sub_df = test_df.copy()
sub_df['target'] = y_pred
sub_df = sub_df[['id', 'target']]
sub_df.to_csv(os.path.join(proj_dir, 'data', 'submissions', 'lr_model_submission_1.csv'), index=False)

Submitting the above gives me a score of 0.81000 and a rank of 778 on the Leaderboard.  The top score on the Leaderboard is currently 0.92266