In [1]:
import nb_utils
proj_dir = nb_utils.proj_path_setup()

In [2]:
#standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

plt.style.use('ggplot')

%matplotlib inline

In [3]:
train_df = pd.read_csv(os.path.join(proj_dir, 'data', 'raw', 'train.csv'))
test_df = pd.read_csv(os.path.join(proj_dir, 'data', 'raw', 'test.csv'))
feature_cols = [col for col in test_df.columns if col != 'id']

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler = StandardScaler()

X_train = scaler.fit_transform(train_df[feature_cols])

y_train = np.array(train_df['target'])

In [6]:
X_train

array([[-0.73403157,  0.36562268, -0.8897276 , -0.88438794, -1.13486936,
        -0.82913603],
       [ 1.06590369, -0.86589692,  0.21952069,  0.28805926,  0.84638411,
         0.02033832],
       [-1.33400999,  0.27208954, -1.19690404,  0.40796863, -0.8780402 ,
         1.53258937],
       ...,
       [ 0.01594146,  0.50592238, -0.83853152,  0.10153357, -0.06352489,
         1.109408  ],
       [-1.48400459,  1.81538625, -1.39315566, -1.17749974, -1.49443017,
        -0.9598244 ],
       [-1.03402078,  0.27208954, -1.22676842, -1.53722786, -0.8780402 ,
        -1.1963081 ]])

In [7]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,

#### Add noise to X data

In [8]:
from models.dae import *

In [23]:
X_train_df = pd.DataFrame(X_train, columns=feature_cols)

In [24]:
noisy_X = add_noise(X_train_df, p=0.30)

In [25]:
noisy_X

gravity        ph      osmo      cond      urea      calc
0   -0.734032  0.365623 -0.889728 -0.884388 -0.878040 -0.829136
1    1.065904 -0.865897  0.219521  0.288059  0.846384  1.096961
2    0.315931  0.272090 -1.196904  0.407969 -0.878040  1.532589
3   -1.484005 -1.629751 -0.893994 -0.084992  0.875736 -0.334387
4    0.465925 -0.663242 -1.226768 -0.484690  0.780342 -0.592652
..        ...       ...       ...       ...       ...       ...
409 -1.034021 -1.162085 -0.531355 -0.005053 -1.494430 -0.804243
410  0.915909 -0.663242 -1.410221 -1.350702 -0.401072 -0.502415
411  0.015941  0.505922  0.070199  0.101534 -0.063525 -0.885145
412 -1.484005  1.815386 -1.393156 -1.177500 -0.966096  2.665222
413 -1.034021  0.272090 -1.226768 -0.005053 -0.878040 -1.196308

[414 rows x 6 columns]

In [18]:
train_df[feature_cols]

gravity    ph  osmo  cond  urea  calc
0      1.013  6.19   443  14.8   124  1.45
1      1.025  5.40   703  23.6   394  4.18
2      1.009  6.13   371  24.5   159  9.04
3      1.021  4.91   442  20.8   398  6.63
4      1.021  5.53   874  17.8   385  2.21
..       ...   ...   ...   ...   ...   ...
409    1.011  5.21   527  21.4    75  1.53
410    1.024  5.53   577  19.7   224  0.77
411    1.018  6.28   455  22.2   270  7.68
412    1.008  7.12   325  12.6    75  1.03
413    1.011  6.13   364   9.9   159  0.27

[414 rows x 6 columns]

In [26]:
import tensorflow as tf
from tensorflow import keras

In [27]:
model = keras.models.Sequential([
    keras.layers.Input(shape=noisy_X.shape[1:]),
    keras.layers.Dense(500, activation='relu'),
    keras.layers.Dense(500, activation='relu'),
    keras.layers.Dense(500, activation='relu'),
    keras.layers.Dense(6)
])

model.compile(loss="mean_squared_error", optimizer=keras.optimizers.Adam(learning_rate=0.001))

In [28]:
early_stopping_cb = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=10)

In [29]:
history = model.fit(noisy_X, X_train_df, epochs=2001,
                    callbacks=[early_stopping_cb])

Epoch 1/2001
13/13 [==============================] - 0s 4ms/step - loss: 0.6424
Epoch 2/2001
13/13 [==============================] - 0s 4ms/step - loss: 0.4575
Epoch 3/2001
13/13 [==============================] - 0s 4ms/step - loss: 0.4161
Epoch 4/2001
13/13 [==============================] - 0s 4ms/step - loss: 0.4009
Epoch 5/2001
13/13 [==============================] - 0s 4ms/step - loss: 0.3877
Epoch 6/2001
13/13 [==============================] - 0s 4ms/step - loss: 0.3749
Epoch 7/2001
13/13 [==============================] - 0s 4ms/step - loss: 0.3613
Epoch 8/2001
13/13 [==============================] - 0s 4ms/step - loss: 0.3583
Epoch 9/2001
13/13 [==============================] - 0s 6ms/step - loss: 0.3487
Epoch 10/2001
13/13 [==============================] - 0s 4ms/step - loss: 0.3231
Epoch 11/2001
13/13 [==============================] - 0s 3ms/step - loss: 0.3073
Epoch 12/2001
13/13 [==============================] - 0s 3ms/step - loss: 0.2916
Epoch 13/2001
13/13 [====

In [30]:
model.save(os.path.join(proj_dir, 'models', 'dae_model_swap_noise_30.h5'))

In [31]:
features_df = extract_features(model, X_train_df)

13/13 [==============================] - 0s 2ms/step


In [32]:
features_df

0         1         2         3         4         5         6     \
0    0.105094  0.000000  0.055305  0.239354  0.000000  0.000000  0.209187   
1    0.100698  0.000000  0.000000  0.000000  0.063757  0.149102  0.000000   
2    0.000000  0.211943  0.000000  0.097726  0.000000  0.000000  0.252990   
3    0.140334  0.061624  0.000000  0.000000  0.001513  0.185923  0.000000   
4    0.008934  0.000000  0.000000  0.000000  0.000000  0.092718  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
409  0.281536  0.044350  0.000000  0.164553  0.000000  0.070411  0.184628   
410  0.271684  0.000000  0.006511  0.132825  0.087225  0.180131  0.000000   
411  0.000000  0.038580  0.106261  0.044047  0.114512  0.000000  0.026933   
412  0.000000  0.052521  0.225045  0.418127  0.000000  0.000000  0.390289   
413  0.084376  0.011557  0.077660  0.206143  0.000000  0.000000  0.222388   

         7     8         9     ...      1490      1491  1492  1493      1494  \
0    0.000000   0.0  0.000000  ...  0.000000  0.000000   0.0   0.0  0.372682   
1    0.046329   0.0  0.000000  ...  0.213341  0.274871   0.0   0.0  0.000000   
2    0.018421   0.0  0.000000  ...  0.579527  0.000000   0.0   0.0  0.000000   
3    0.115523   0.0  0.000000  ...  0.247766  0.232137   0.0   0.0  0.000000   
4    0.000000   0.0  0.135379  ...  0.000000  0.307541   0.0   0.0  0.000000   
..        ...   ...       ...  ...       ...       ...   ...   ...       ...   
409  0.000000   0.0  0.000000  ...  0.000000  0.000000   0.0   0.0  0.000000   
410  0.000000   0.0  0.000000  ...  0.000000  0.000000   0.0   0.0  0.000000   
411  0.193787   0.0  0.000000  ...  0.000000  0.000000   0.0   0.0  0.000000   
412  0.093095   0.0  0.027577  ...  0.000000  0.000000   0.0   0.0  0.474712   
413  0.011962   0.0  0.003069  ...  0.000000  0.000000   0.0   0.0  0.484163   

         1495      1496      1497      1498  1499  
0    0.000000  0.000000  0.000000  0.511415   0.0  
1    0.133355  0.273627  0.027265  0.000000   0.0  
2    0.000000  0.000000  0.000000  0.265349   0.0  
3    0.000000  0.502687  0.000000  0.000000   0.0  
4    0.000000  0.249126  0.000000  0.020367   0.0  
..        ...       ...       ...       ...   ...  
409  0.000000  0.015707  0.000000  0.000000   0.0  
410  0.000000  0.000000  0.000000  0.000000   0.0  
411  0.097417  0.020793  0.000000  0.172312   0.0  
412  0.000000  0.000000  0.000000  0.890431   0.0  
413  0.000000  0.000000  0.000000  0.556341   0.0  

[414 rows x 1500 columns]

#### Test logistic model fit using extracted dae features

In [34]:
from sklearn.linear_model import LogisticRegression


In [35]:
lr_model = LogisticRegression()
lr_model.fit(features_df, y_train)

LogisticRegression()

In [36]:
y_pred = lr_model.predict(features_df)

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_train, y_pred)

0.8599033816425121

#### Encode test data and extract features

In [39]:
X_test = scaler.transform(test_df[feature_cols])

In [40]:
X_test_df = pd.DataFrame(X_test, columns=feature_cols)
noisy_X_test = add_noise(X_test_df, p=0.30)

In [41]:
history = model.fit(noisy_X_test, X_test_df, epochs=2001,
                    callbacks=[early_stopping_cb])

Epoch 1/2001
9/9 [==============================] - 0s 4ms/step - loss: 0.6315
Epoch 2/2001
9/9 [==============================] - 0s 4ms/step - loss: 0.3718
Epoch 3/2001
9/9 [==============================] - 0s 4ms/step - loss: 0.2782
Epoch 4/2001
9/9 [==============================] - 0s 3ms/step - loss: 0.2229
Epoch 5/2001
9/9 [==============================] - 0s 4ms/step - loss: 0.1783
Epoch 6/2001
9/9 [==============================] - 0s 3ms/step - loss: 0.1546
Epoch 7/2001
9/9 [==============================] - 0s 3ms/step - loss: 0.1338
Epoch 8/2001
9/9 [==============================] - 0s 4ms/step - loss: 0.1154
Epoch 9/2001
9/9 [==============================] - 0s 4ms/step - loss: 0.1029
Epoch 10/2001
9/9 [==============================] - 0s 3ms/step - loss: 0.0919
Epoch 11/2001
9/9 [==============================] - 0s 3ms/step - loss: 0.0788
Epoch 12/2001
9/9 [==============================] - 0s 3ms/step - loss: 0.0697
Epoch 13/2001
9/9 [==============================

In [42]:
test_features_df = extract_features(model, X_test_df)

9/9 [==============================] - 0s 2ms/step


In [43]:
y_pred = lr_model.predict(test_features_df)

In [44]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1], dtype=int64)

In [45]:
sub_df = test_df.copy()
sub_df['target'] = y_pred
sub_df = sub_df[['id', 'target']]
sub_df.to_csv(os.path.join(proj_dir, 'data', 'submissions', 'dae_sn30_model_submission_1.csv'), index=False)

Submitting the above gives me a score of 0.75333 ... even worse than the lr model alone.  Obviously need to tune at least the swap_noise probability.